# Generated by Django 2.2.4 on 2019-08-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190806_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviedetails',
            name='actors',
        ),
        migrations.AddField(
            model_name='moviedetails',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, to='movie.Actor'),
        ),
    ]
