# Generated by Django 2.2.4 on 2019-08-06 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20190806_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviedetails',
            name='actors',
            field=models.ManyToManyField(blank=True, null=True, related_name='actors', to='movie.Actor'),
        ),
    ]
